### ISSUE TITLE
Support uplink retransmissions

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#356] opened 2019-03-23 11:48 UTC
**Summary:** 

NS does not support retransmissions of uplinks

**Why do we need this?**

To be fully compliant with LoRaWAN and make users happy

**What is already there? What do you see now?**

No retransmission support

**What is missing? What do you want to see?**

Retransmission support

**How do you propose to implement this?**

Use `NbTrans` parameter and a counter to count the number of (possible) retransmissions and drop uplinks exceeding the `NbTrans`.
If retransmission is encountered, the device MAC state should probably be rolled back, since it implies that the downlink(if any) was not received.
We may want to add additional "retransmission" message to send to AS from NS.

**Comment by johanstokking** [comment] 2019-03-26 15:02
Duplicate of #325 ?

**Comment by rvolosatovs** [comment] 2019-04-15 09:44
No, #325 was about a confusing logging statement. This one is about supporting the feature.

**Closed** 2019-05-10 09:50 UTC
Labels: c/network server, prio/high
