### ISSUE TITLE
Serve or link to deployment CA certificates

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#2712] opened 2020-06-11 13:11 UTC
#### Summary

Serve or link to CA certificates from within a deployment, or provide instructions for figuring out which certs a deployment is using.

#### Why do we need this?

Some gateway manufacturers don't include common CA certificates on their hardware, and require users to manually supply certificates. This means we have to either tell them which certificate their deployment uses, or provide a way to download the public key / trust.

Per @adriansmares comments, this defeats the purpose of CAs, but if we don't do it, it breaks LBS on some gateways.

<img width="575" alt="Screenshot 2020-06-10 at 13 59 09" src="https://user-images.githubusercontent.com/6963436/84388764-65b63a80-abf5-11ea-9d47-0195b5e9944b.png">

#### What is already there? What do you see now?

No documentation about certificates in docs. Some info in confluence about CH.

#### What is missing? What do you want to see?

Serve or link to CA certificates from within a deployment, or provide instructions for figuring out which certs a deployment is using.

#### How do you propose to implement this?

Serve a zip with key and trust, or provide a link to CA where they can be downloaded.

#### Can you do this yourself and submit a Pull Request?

No

**Comment by KrishnaIyer** [comment] 2020-06-11 13:13
I'll take this

**Comment by johanstokking** [comment] 2020-06-12 10:03
Isn't this a duplicate of https://github.com/TheThingsIndustries/lorawan-stack/issues/2192?

**Comment by benolayinka** [comment] 2020-06-16 13:15
> Isn't this a duplicate of [TheThingsIndustries/lorawan-stack#2192](https://github.com/TheThingsIndustries/lorawan-stack/issues/2192)?

Yep but I think @KrishnaIyer is going to handle TTES differently?

**Comment by benolayinka** [comment] 2020-07-08 13:07
@KrishnaIyer what's the plan?

**Comment by KrishnaIyer** [comment] 2020-07-08 13:30
I have no time to look into this currently. Feel free to assign someone else if necessary.

**Comment by benolayinka** [comment] 2020-07-08 14:42
@johanstokking @htdvisser do you think we need to do something now to handle LBS gateway forms like this?

<img width="575" alt="Screenshot 2020-06-10 at 13 59 09" src="https://user-images.githubusercontent.com/6963436/84388764-65b63a80-abf5-11ea-9d47-0195b5e9944b.png">

**Comment by johanstokking** [comment] 2020-07-08 19:59
> > Isn't this a duplicate of [TheThingsIndustries/lorawan-stack#2192](https://github.com/TheThingsIndustries/lorawan-stack/issues/2192)?
> 
> 
> 
> Yep but I think @KrishnaIyer is going to handle TTES differently?

For TTS, people know what certs they use to setup the stack, so this is not relevant here. Let’s continue the discussion in https://github.com/TheThingsIndustries/lorawan-stack/issues/2192.

**Closed** 2020-07-08 19:59 UTC
Labels: c/console
