### ISSUE TITLE
No live data showing in application

### ISSUE THREAD

**Issue by mczakk** [TheThingsNetwork/lorawan-stack#5872] opened 2022-10-13 09:54 UTC
### Summary

No 'live data' showing for gateways or application end devices
![ttncs](https://user-images.githubusercontent.com/6179722/195565115-2702f0f7-4bce-425f-9e54-f297ae1152d1.jpg)
![ttnss](https://user-images.githubusercontent.com/6179722/195565123-8e5fd825-18a9-41e0-b0b6-f03e5efe9bd1.jpg)
![ttnnw](https://user-images.githubusercontent.com/6179722/195565125-22fc3db8-b016-4b6e-8e9c-a2a120430be7.jpg)

### Steps to Reproduce

open console
select application
select end devices
select live data

### Current Result

no live data shown

### Expected Result

live data shown

### Deployment

The Things Stack Community Edition

### The Things Stack Version

v3.22.0

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [ ] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by descartes** [comment] 2022-10-14 07:13
Others have no issues with Linux. I have no issues with macOS Safari / Chrome / Firefox. Suspect Windows + yet to be identified antivirus is the target.

**Comment by mczakk** [comment] 2022-10-14 08:11
As stated on the TTN forum, Windows + Sophos endpoint agent seems to be a common theme linking those of us with an issue

**Comment by descartes** [comment] 2022-10-14 08:15
As stated on the TTN forum, links help speed things up: https://www.thethingsnetwork.org/forum/t/no-live-data-showing-in-console/59347?u=descartes

**Comment by NicolasMrad** [comment] 2022-10-19 15:19
Can you please provide us with the browser being used and it's version, and the OS will help as well

**Comment by HeadBoffin** [comment] 2022-10-19 15:40
> Can you please provide us with the browser being used and it's version, and the OS will help as well

The thread pretty much tells you everything - that Sophos blocks browsers on Windows - both people reporting it are using corporate machines so probably aren't in a position to give you specific versions.

**Comment by kschiffer** [comment] 2022-10-19 16:01
Thanks for filing this issue @mczakk.

Unfortunately, we don't usually fix issues that are caused by the interception of connections or tampering with frontend code from third-party applications. If the Console is being obstructed by a security application, it is a matter of fine-tuning the configuration or overall shutdown of such application to resolve this issue. It is not feasible for us to take into consideration any third-party and/or security setup when developing TTS Console.

Frontend-wise there have not been any recent changes as to how events are ingested or processed, so I believe that this is not related to any of our changes. @adriansmares do you know of any backend changes to the event server that might have caused events to be caught by security apps?

Closing this issue now. If there is any new info pointing towards this issue being caused by some problem on our side, I will reopen this.

**Closed as completed by kschiffer** 2022-10-19 16:01 UTC
Labels: needs/triage

**Comment by descartes** [comment] 2022-10-19 16:10
I didn't report this and neither did my alter ego, it was someone else who was told to open the issue by TTI staff in a rather clumsy interaction on the forum, so I was looking to join up the dots so we could arrive at a conclusion.

I wouldn't expect you to fix this issue either.

**Comment by kschiffer** [comment] 2022-10-19 16:12
Oh yeah, I realize I had a wrong mention in my earlier post. Mea culpa.

**Comment by adriansmares** [comment] 2022-10-19 16:13
Hi,

I am not aware of any backend changes related to this, but it's indeed probably Sophos.

The event streams are achieved using server side events over HTTP, and Sophos seems to not like that:
https://community.sophos.com/on-premise-endpoint/f/sophos-endpoint-software/74878/server-sent-events-blocked-by-download-scanner
https://community.sophos.com/free-tools/f/discussions/5750/sophos-av-blocks-server-sent-events-sse-on-mac-os-x-yosemite
https://stackoverflow.com/questions/62129788/on-a-machine-running-sophos-why-do-all-my-browsers-fail-to-receive-server-sent

I don't think there is much we can do here to be honest. I expect that other websites that use server side events will show the same symptoms. What is weird is that past reports seem to say that this occurs only via HTTP, but maybe they are spoofing HTTPS connections too (since they manage the machines).

**Comment by lucaesposto** [comment] 2023-06-21 11:05
Hi,
same issue here.

------------------
TTS version: 3.26.0
OS: Win10
Browser: Chrome 114.0.5735.133
------------------

We temporarily shut down Sophos Endpoint Agent but this error persists.

The strangest behaviour is that TTI console occasionally shows events as expected.

This error is shown in the browser console when opening an end-device page from his application:

axios.cjs:2401     GET https://lorhi.tecnodatasrl.com:4443/api/v3/as/applications/milesight-am307-app/link?field_mask=skip_payload_crypto,default_formatters 404
(anonymous) @ axios.cjs:2401
xhr @ axios.cjs:2199
be @ axios.cjs:2501
Promise.then (async)
request @ axios.cjs:2835
(anonymous) @ axios.cjs:6
(anonymous) @ http.js:209
d @ runtime.js:64
(anonymous) @ runtime.js:299
(anonymous) @ runtime.js:124
d @ runtime.js:64
T @ runtime.js:363
(anonymous) @ runtime.js:273
(anonymous) @ runtime.js:124
t @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ http.js:304
t.<computed>.<computed> @ index.js:102
(anonymous) @ link.js:52
d @ runtime.js:64
(anonymous) @ runtime.js:299
(anonymous) @ runtime.js:124
t @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ link.js:71
(anonymous) @ applications.js:169
y @ regeneratorRuntime.js:50
(anonymous) @ regeneratorRuntime.js:131
(anonymous) @ regeneratorRuntime.js:75
r @ asyncToGenerator.js:4
s @ asyncToGenerator.js:23
(anonymous) @ asyncToGenerator.js:28
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:20
(anonymous) @ applications.js:161
(anonymous) @ create-request-logic.js:130
y @ regeneratorRuntime.js:50
(anonymous) @ regeneratorRuntime.js:131
(anonymous) @ regeneratorRuntime.js:75
r @ asyncToGenerator.js:4
s @ asyncToGenerator.js:23
(anonymous) @ asyncToGenerator.js:28
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:20
(anonymous) @ create-request-logic.js:83
it @ execProcessFn.js:13
(anonymous) @ logicWrapper.js:116
t._execute @ AsyncAction.js:64
t.execute @ AsyncAction.js:52
t.flush @ AsapScheduler.js:18
(anonymous) @ Immediate.js:16
Promise.then (async)
t.requestAsyncId @ Immediate.js:16
t.schedule @ AsyncAction.js:28
e.schedule @ Scheduler.js:13
t.schedule @ AsyncScheduler.js:31
(anonymous) @ logicWrapper.js:114
t._next @ tap.js:45
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t._next @ Subscriber.js:76
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:23
(anonymous) @ asyncToGenerator.js:28
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:20
(anonymous) @ index.js:82
(anonymous) @ use-request.js:31
Iu @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Ou @ react-dom.production.min.js:261
vu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Ki @ react-dom.production.min.js:123
Wi @ react-dom.production.min.js:122
Oe @ react-dom.production.min.js:292
qt @ react-dom.production.min.js:73
