### ISSUE TITLE
Problem with recreating deleted user with same email and username again

### ISSUE THREAD

**Issue by thevirtualdj** [TheThingsNetwork/lorawan-stack#2924] opened 2020-07-16 11:35 UTC
Problem with recreating deleted user with same email and username again: 
Previously I deleted this user and want to add it again. 
Did I misconfigured again or ? 

![image](https://user-images.githubusercontent.com/102127/87666462-f50cbb80-c768-11ea-9d6a-ca3c3e24706b.png)

**Comment by htdvisser** [comment] 2020-08-24 11:14
Invalid issue (does not respect issue template).

Duplicate of #604

**Closed by htdvisser** 2020-08-24 11:14 UTC
