### ISSUE TITLE
Add support for LoRaWAN Regional Parameters RP2 1.0.{0,1,2}

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#3578] opened 2020-12-09 15:08 UTC
#### Summary

We need to add support for the new regional parameters documents that go with LoRaWAN 1.0.4.

See https://github.com/TheThingsNetwork/lorawan-stack/issues/2784#issuecomment-648735723 for the story about the naming scheme

#### How do you propose to implement this?

PDFs are available on Drive or from the LoRa Alliance website.

#### How do you propose to test this?

🤷

**Comment by kschiffer** [comment] 2020-12-21 15:02
Duplicate of #3513

**Closed as completed by kschiffer** 2020-12-21 15:02 UTC
Labels: c/network server
