### ISSUE TITLE
 Build stand-alone Node SDK for TTSE APIs

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsNetwork/lorawan-stack#4244] opened 2021-06-08 10:04 UTC
#### Summary
A stand-alone Node SDK for TTSE APIs, to integrate with existing Node application

#### Why do we need this?
Having SDK in a programming language helps the developer to integrate quickly than integrating the REST APIs

#### What is already there? What do you see now?
Only JavaScript SDK is present as of now

#### What is missing? What do you want to see?
Node SDK along with SDK integration documentation

#### Environment
...

#### How do you propose to implement this?
...

#### How do you propose to test this?
...

#### Can you do this yourself and submit a Pull Request?
Nope

**Comment by adriansmares** [comment] 2022-08-11 13:36
Duplicate of https://github.com/TheThingsNetwork/lorawan-stack/issues/3058.

**Closed as completed by adriansmares** 2022-08-11 13:36 UTC
