### ISSUE TITLE
gRPC transient failures when idle

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#62] opened 2019-01-29 18:02 UTC
**Summary:** 

Seeing regularly ready to transient failure to connecting to ready state changes when idle.

**Steps to Reproduce:** 

1. Enable debug log level
2. Run the stack
3. Do nothing for a while

**What do you see now?**

```
 DEBUG transport: loopyWriter.run returning. connection error: desc = "transport is closing" namespace=grpc
 DEBUG Subchannel Connectivity change to TRANSIENT_FAILURE namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc000467650, TRANSIENT_FAILURE namespace=grpc
 DEBUG Subchannel Connectivity change to TRANSIENT_FAILURE namespace=grpc
 DEBUG transport: loopyWriter.run returning. connection error: desc = "transport is closing" namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc0009fc830, TRANSIENT_FAILURE namespace=grpc
 DEBUG transport: loopyWriter.run returning. connection error: desc = "transport is closing" namespace=grpc
 DEBUG Subchannel Connectivity change to TRANSIENT_FAILURE namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc000430270, TRANSIENT_FAILURE namespace=grpc
 DEBUG transport: loopyWriter.run returning. connection error: desc = "transport is closing" namespace=grpc
 DEBUG Subchannel Connectivity change to TRANSIENT_FAILURE namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc000674380, TRANSIENT_FAILURE namespace=grpc
 DEBUG Subchannel Connectivity change to CONNECTING namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc000467650, CONNECTING namespace=grpc
 DEBUG Subchannel Connectivity change to READY  namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc000467650, READY namespace=grpc
 DEBUG transport: loopyWriter.run returning. connection error: desc = "transport is closing" namespace=grpc
 DEBUG Subchannel Connectivity change to TRANSIENT_FAILURE namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc0009fcf10, TRANSIENT_FAILURE namespace=grpc
 DEBUG transport: loopyWriter.run returning. connection error: desc = "transport is closing" namespace=grpc
 DEBUG Subchannel Connectivity change to TRANSIENT_FAILURE namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc0009fcdf0, TRANSIENT_FAILURE namespace=grpc
 DEBUG Subchannel Connectivity change to CONNECTING namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc0009fc830, CONNECTING namespace=grpc
 DEBUG Subchannel Connectivity change to READY  namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc0009fc830, READY namespace=grpc
 DEBUG Subchannel Connectivity change to CONNECTING namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc000674380, CONNECTING namespace=grpc
 DEBUG Subchannel Connectivity change to READY  namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc000674380, READY namespace=grpc
 DEBUG Subchannel Connectivity change to CONNECTING namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc000430270, CONNECTING namespace=grpc
 DEBUG Subchannel Connectivity change to READY  namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc000430270, READY namespace=grpc
 DEBUG Subchannel Connectivity change to CONNECTING namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc0009fcf10, CONNECTING namespace=grpc
 DEBUG Subchannel Connectivity change to READY  namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc0009fcf10, READY namespace=grpc
 DEBUG Subchannel Connectivity change to CONNECTING namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc0009fcdf0, CONNECTING namespace=grpc
 DEBUG Subchannel Connectivity change to READY  namespace=grpc
 DEBUG pickfirstBalancer: HandleSubConnStateChange: 0xc0009fcdf0, READY namespace=grpc
```

**What do you want to see instead?**

Is this normal? If so it's fine. Otherwise, is this problematic?

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1565 by @johanstokking

**Comment by htdvisser** [comment] 2019-04-17 12:58
Can't reproduce this. Let's close this and see if it pops up again in the future.

**Closed by htdvisser** 2019-04-17 12:58 UTC
Labels: c/shared, question

**Comment by johanstokking** [comment] 2019-04-23 11:49
Fine, haven't seen it either for a long time.
