### ISSUE TITLE
Support Private Network Connection on The Things Gateway

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#16] opened 2019-01-29 17:59 UTC
**Summary:** 

In ttnv2, the configuration sent by the account server to The Things Gateway cannot be configured to support private networks with custom Router IPs.

References #68 

**Why do we need this?**

This feature would add value to The Things Gateway making it a useful tool for new customers to evaluate our V3 service.

**What is already there? What do you see now?**

The gateway is always hard-coded to PCN routers.

**What is missing? What do you want to see?**

The gateway should connect to the `gatewayserveraddress` from the gateway settings.

**How do you propose to implement this?**

1. The Gateway connects to the hard-coded `https://account.thethingsnetwork.org` to fetch configuration. 
2. The IS sends the frequency plans as well including the gateway-server address configured in its settings.
3. The Gateway now connects to the `gatewayserver-IP:mqtt-port` to send uplinks/receive downlinks.

**What can you do yourself and what do you need help with?**

I can create a PR.

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/770 by @KrishnaIyer

**Comment by htdvisser** [comment] 2019-02-13 12:12
Reassigning this one to me, as it's basically a duplicate of #68

**Comment by htdvisser** [comment] 2019-03-04 15:12
Really duplicate of #68

**Closed by htdvisser** 2019-03-04 15:12 UTC
Labels: c/identity server, goldplating
