### ISSUE TITLE
Console Device Overview lacks Array formatting for session keys

### ISSUE THREAD

**Issue by lnlp** [TheThingsNetwork/lorawan-stack#3807] opened 2021-02-15 14:22 UTC
#### Summary
`Console | <Application> | End devices | <ABP Device> | Overview` lacks array formatting for session keys NwkSKey, SNwkSIntKey, NwkSEncKey and AppSkey.

This is reported as bug because in V2 Console formatters for NwkSKey and AppSKey are available.

#### Steps to Reproduce
See `Console | <Application> | End devices | <ABP Device> | Overview`.
Select a device that uses ABP activation.

#### What do you see now?
The following will show up:

![ABP](https://user-images.githubusercontent.com/40600181/107956611-a8f45480-6f9f-11eb-8af4-1d5a54786cad.png)

Select the `Toggle visibility` icon of the different session keys to show their value.
Notice that this will not reveal any `Toggle array formatting` buttons:

![ABP NO Formatters](https://user-images.githubusercontent.com/40600181/107956624-b0b3f900-6f9f-11eb-8682-f8a1fcce9186.png)

When selecting a device that uses OTAA instead of ABP activation the following will be shown:

![OTAA](https://user-images.githubusercontent.com/40600181/107956645-bb6e8e00-6f9f-11eb-84a1-e499d1820ff0.png)

When selecting the `Toggle visibility` icon for AppKey this not only makes the key visible but also reveals a `Toggle array formatting` icon:

![OTAA Formatter](https://user-images.githubusercontent.com/40600181/107956658-c1646f00-6f9f-11eb-88d0-0f00cfda3292.png)

#### What do you want to see instead?
When the keys are made visible by selecting the `Toggle visibility` icon this should also reveal a `Toggle array formatting` icon (with corresponding functionality) for each key.

#### Environment
Not environment-specific.

#### How do you propose to implement this?
Just add it.

#### Can you do this yourself and submit a Pull Request?
No

**Comment by kschiffer** [comment] 2021-02-15 16:23
This has been fixed by #3752 already, or what do I miss here?

It will be in the next release.

**Comment by bafonins** [comment] 2021-02-15 17:07
Indeed, its already implemented! Closing this.

**Closed as completed by bafonins** 2021-02-15 17:07 UTC
Labels: c/console, ui/web

**Comment by lnlp** [comment] 2021-02-16 09:07
I have searched for a similar issue but could not find it.
Apparently #3752 has been fixed and closed 7 days ago already.

If issues are still present in the current product (production) then one is going to search in open issues if the issue is already reported, not in issues that have already been closed. This is why `is:issue is:open` is the default search filter.
From user perspective it will be more useful if issues are closed when the release in which they are fixed has been released / rolled-out to production, or at least be able to see an overview of issues that have been fixed and closed already but are not yet released / not yet in production.

Closing issues that are not yet in production hides them from users who want to report issues.

**Comment by kschiffer** [comment] 2021-02-16 11:37
Hi @lnlp, I understand your issue but we have to stay pragmatic on the development side. For us the issue is resolved as soon as the fix has been merged. Keeping them open until the release will lead to many issues being kept open well after a fix was released, since it would be require us to go over all the issues once more after the release and we'd likely forget doing so for some.

We are currently working on increasing our release cycles so that the gap between closed issue and release should become smaller in the future.

> or at least be able to see an overview of issues that have been fixed and closed already but are not yet released / not yet in production.

You can do this using the [CHANGELOG.md](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.11/CHANGELOG.md), which also contains the currently unreleased changes at the very top (set to be in the next release). Note though that on TTN v3, we are not running the Open Source version of the stack, but The Things Stack Enterprise. So due to this and other technicalities of our release process, there can be a small gap between the state of this file and the actual release that is currently running on TTN.
