### ISSUE TITLE
Add RP002 PHY versions

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#3150] opened 2020-08-26 12:54 UTC
#### Summary

Add RP002 PHY versions
Refs https://github.com/TheThingsNetwork/lorawan-stack/pull/3146#discussion_r477207656

#### Why do we need this?

To support recent versions of LoRaWAN specification

#### What is missing? What do you want to see?

RP002 PHY version support

#### How do you propose to implement this?

Probably just add new enums to protos, but we might need to deal with some specifics of versioning scheme change, e.g. set up aliases, not sure

#### How do you propose to test this?

create devices using new PHY versions and test

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by johanstokking** [comment] 2021-03-01 14:31
Duplicate of #3513

**Closed as completed by johanstokking** 2021-03-01 14:31 UTC
Labels: c/shared, compat/api
