### ISSUE TITLE
Time when devices are "created" are not updated

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#3517] opened 2020-11-24 10:25 UTC
#### Summary
See the 2 devices which show `Now` below the `Created` column.
<img width="1035" alt="Screenshot 2020-11-24 at 11 20 10" src="https://user-images.githubusercontent.com/17290639/100081362-36178980-2e47-11eb-8766-15fdf6e4d6d7.png">

#### Steps to Reproduce

1. Look at the application in TTIs tenant (only access for admins) - [link](https://tti.eu1.cloud.thethings.industries/console/applications/smart-campervan/devices)
2. OR, create a new devices, and watch the device overview page.

#### What do you see now?
See img above.

#### What do you want to see instead?
The created-field being updated.

#### Environment
v3.10

#### How do you propose to test this?
Add new devices locally

**Comment by laurensslats** [comment] 2020-11-24 10:29
Note.

This doesn't happen when adding new devices. It only happend with 2 devices I added in the past.

See:
<img width="1017" alt="Screenshot 2020-11-24 at 11 27 44" src="https://user-images.githubusercontent.com/17290639/100082100-16cd2c00-2e48-11eb-8244-212877a07aa1.png">

**Comment by asmulko** [comment] 2020-12-29 13:45
@bafonins @kschiffer unfortunately PR #3588 did not solve the issue. Could someone please point me in the right direction or perhaps take a look at this issue themselves?

**Comment by kschiffer** [comment] 2021-06-01 13:02
I think we can close this since the creation date is not shown anymore in the device list (via #3832) . Also we haven't been able to reproduce the issue.

**Closed as completed by kschiffer** 2021-06-01 13:02 UTC
Labels: c/console, ui/web
