### ISSUE TITLE
Strange login redirect

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#3395] opened 2020-10-22 08:47 UTC
#### Summary

When I login with a newly created account, I'm redirected to an unformatted oauth page and I have to reenter the console url to get to the console. 

#### Steps to Reproduce

1. Create an unapproved account
2. Login

#### What do you see now?

<img width="1447" alt="Screenshot 2020-10-22 at 10 26 38" src="https://user-images.githubusercontent.com/6963436/96847680-c54e0d80-1453-11eb-9df9-22db4509ef5f.png">

#### What do you want to see instead?

A redirect to the console

#### Environment

3.10

#### Can you do this yourself and submit a Pull Request?

@kschiffer

**Comment by kschiffer** [comment] 2020-10-22 09:23
Duplicate of https://github.com/TheThingsIndustries/lorawan-stack/issues/1968

See also https://github.com/TheThingsIndustries/infrastructure/issues/757

**Closed as completed by kschiffer** 2020-10-22 09:23 UTC
Labels: bug
