### ISSUE TITLE
Downlink tasks added more often than necessary

### ISSUE THREAD

**Issue by virtualguy** [TheThingsNetwork/lorawan-stack#2422] opened 2020-04-27 10:36 UTC
#### Summary
I can see warnings that the NS is unable to schedule downlinks however as it is a multicast device I don't expect it to be generating downlinks by itself. Is this DevStatusReq or other MAC commands?

Is this related to #1637 / https://github.com/TheThingsNetwork/lorawan-stack/pull/2418

#### Steps to Reproduce

Create multicast device as per the [guide](https://thethingsstack.io/v3.7.2/guides/class-c-multicast/)
1. `ttn-lw-cli applications create app1`
2. `ttn-lw-cli end-devices create app1 mc1 \
  --frequency-plan-id EU_863_870 \
  --lorawan-version 1.0.3 \
  --lorawan-phy-version 1.0.3-a \
  --session.dev-addr 00E4304D \
  --session.keys.app-s-key.key A0CAD5A30036DBE03096EB67CA975BAA \
  --session.keys.nwk-s-key.key B7F3E161BC9D4388E6C788A0C547F255 \
  --multicast \
  --supports-class-c`
3. Watch warnings in logs

#### What do you see now?

WARN Failed to generate class B/C downlink, skip class B/C downlink slot dev_addr=00E4304D device_class=CLASS_C device_uid=app1.mc1 downlink_type=data error=error:pkg/networkserver:no_downlink (no downlink to send) namespace=networkserver started_at=2020-04-27 20:11:09.982016324 +0000 UTC

#### What do you want to see instead?

Silence is bliss

#### Environment
ttn-lw-stack v3.7.2

#### How do you propose to implement this?
Skip sending MAC commands for 'virtual' multicast devices

#### Can you do this yourself and submit a Pull Request?
@rvolosatovs ?
...

**Comment by rvolosatovs** [comment] 2020-04-28 10:20
> error=error:pkg/networkserver:no_downlink (no downlink to send)

This is simply a cosmetic issue, which does not indicate that anything is broken. I'm still not completely sure what the cause of it is, but most probably it will be fixed by https://github.com/TheThingsNetwork/lorawan-stack/pull/2418.

**Closed** 2020-05-06 09:16 UTC
Labels: bug, c/network server, s/in progress
