### ISSUE TITLE
Improve MAC command documentation

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#2699] opened 2020-06-10 14:09 UTC
#### Summary
In the docs, you can only find the fields, but not the possible values that need to be set https://enterprise.thethingsstack.io/latest/reference/api/end_device/

Running `$ ttn-lw-cli end-devices update --help` provides some extra info, but you still need to know the LoRaWAN specs to know i.e. that DATA_RATE_3 means SF9, 125 KHz.

#### Why do we need this ?
Better experience when changing MAC settings

#### What is already there? What do you see now?
https://enterprise.thethingsstack.io/latest/reference/api/end_device/

#### What is missing? What do you want to see?
Includes the possible values that can be set for each field.

#### Can you do this yourself and submit a Pull Request?
Will make a start myself.

**Comment by htdvisser** [comment] 2020-08-24 15:10
Duplicate of https://github.com/TheThingsNetwork/lorawan-stack/issues/2914

**Comment by rvolosatovs** [comment] 2020-08-25 13:06
Is there a reason not to close this if we have #2914 already?

**Closed** 2020-08-25 14:00 UTC
Labels: documentation, duplicate
