### ISSUE TITLE
Setting antenna gain doesnt take immediate affect

### ISSUE THREAD

**Issue by virtualguy** [TheThingsNetwork/lorawan-stack#6979] opened 2024-03-07 21:20 UTC
### Summary

When changing the antenna gain on a gateway it has no affect until a gateway disconnects. It takes a full disconnection timeout until messages start being scheduled with the new TX power

### Steps to Reproduce

1. Gateway connected with antenna.gain set to 0
2. Using ttn-lw-cli set antenna gain to 10
3. Observe downlinks still being scheduled at the same tx power (i.e. 30dBm for AU915)

### Current Result

Transmit power doesnt change until gateway disconnects

### Expected Result

Gain takes affect immediately and transmit power changes

### Deployment

The Things Stack Open Source (self-hosted)

### The Things Stack Version

3.28.0

### Proposed Fix

Compare changes to the antenna properties and require a gateway disconnect [here](https://github.com/halter-corp/lorawan-stack/blob/feat/halter-release-v3.28.0/pkg/gatewayserver/gatewayserver.go#L595)

### Contributing

- [X] I can help by doing more research.
- [X] I can help by implementing a fix after the proposal above is approved.
- [X] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment] 2024-03-11 14:32
This is actually by design. Gateway settings are stored in the Identity Server and gateways connect to the Gateway Server. These may be in different clusters and we use the gateway reconnection to sync settings.

If you are using LBS, we need to report the [antenna gain to the gateway](https://lora-developers.semtech.com/build/software/lora-basics/lora-basics-for-gateways/?url=gw_v1.5.html) during the connection. This means that the changes cannot reflect in the same connection.

For UDP, I don't see a technical reason for waiting for a new connection other than the TTS architecture.

What we can do is to trigger a server-side disconnect of the gateway if the antenna gain is adjusted? Then the gateway can reconnect and fetch new data. Would that be something that works for your requirement?

**Comment by virtualguy** [comment] 2024-03-11 18:30
Yes that sounds good, a server side forced reconnection should do the trick

**Comment by KrishnaIyer** [comment] 2024-03-12 09:28
Ok thanks. Do  @adriansmares or @johanstokking see a reason against triggering a gateway reconnection on antenna gain change? We have this mechanism already for changes in the location type.

**Comment by adriansmares** [comment] 2024-03-12 09:34
I don't see a reason against it - we probably should just update this check to also look at the antenna gain.
https://github.com/TheThingsNetwork/lorawan-stack/blob/ed1a5f885d9d9a3b23d033a28cb85bc358669a3b/pkg/gatewayserver/gatewayserver.go#L601-L630

**Comment by johanstokking** [comment] 2024-03-12 10:35
Yes, sounds like a good reason to reconnect.

**Comment by KrishnaIyer** [comment] 2024-05-29 14:40
This is completed and will be released as part of `v3.30.2`

**Closed as completed by KrishnaIyer** 2024-05-29 14:40 UTC
Labels: c/gateway server, good first issue
