### ISSUE TITLE
Nil pointer panic in ttn-lw-cli login

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#242] opened 2019-03-06 08:20 UTC
**Summary:** 

There is a nil pointer panic in `ttn-lw-cli login`.

Reported on Slack by [johanntagle](https://thethingsnetwork.slack.com/team/U6F304SKS).

**Steps to Reproduce:** 

1. Run `ttn-lw-cli login`
2. Under certain circumstances it panics with a nil pointer

**What do you see now?**

```
# ttn-lw-cli login                                                                     
panic: runtime error: invalid memory address or nil pointer dereference                                                   
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf1da13]                                                    
                                                                                                                          
goroutine 1 [running]:                                                                                                    
go.thethings.network/lorawan-stack/cmd/ttn-lw-cli/commands.glob..func67(0x1bf1000, 0x1c381a8, 0x0, 0x0, 0x0, 0x0)         
        /root/lorawan-stack/cmd/ttn-lw-cli/commands/login.go:73 +0x293                                                    
github.com/spf13/cobra.(*Command).execute(0x1bf1000, 0x1c381a8, 0x0, 0x0, 0x1bf1000, 0x1c381a8)                           
        /root/work/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465              
```

**What do you want to see instead?**

It should either work, or return an error. Definitely not panic.

**How do you propose to implement this?**

I suspect it has to do with the listener being accessed before checking for an error in creating it. 

**Environment:**

CLI (from master). OS doesn't seem to make a difference.

**What can you do yourself and what do you need help with?**

I'll submit a PR to fix this.

**Comment by johanstokking** [comment] 2019-03-06 08:35
Duplicate of https://github.com/TheThingsNetwork/lorawan-stack/issues/227; more information there as well.

**Closed by johanstokking** 2019-03-06 08:35 UTC
Labels: bug, c/cli
