### ISSUE TITLE
Constant password change on 'Create new user' afterlogin on v3.8.6 until page refresh. 

### ISSUE THREAD

**Issue by thevirtualdj** [TheThingsNetwork/lorawan-stack#2923] opened 2020-07-16 09:05 UTC
Constant password change on 'Create new user' afterlogin on v3.4.6 until page refresh. 

Implemented the stack on public server and on Create new user everything is fine but after we log in user has to change pass or logout. 
On every option after change or logout, when we log in again it says change password again. 
![loging_change_pass](https://user-images.githubusercontent.com/102127/87652287-4d858e00-c754-11ea-873e-a7b2543db921.jpg)

**Comment by KrishnaIyer** [comment] 2020-07-16 09:09
Please upgrade your version to the latest. We've `3.8.7` released yesterday. We don't provide fixes to versions older than the previous minor (currently lesser than `3.7.x`)

**Comment by KrishnaIyer** [comment] 2020-07-16 09:10
Oops. Wrong button

**Comment by thevirtualdj** [comment] 2020-07-16 09:17
Sorry i made a typo 3.4.6 - 3.8.6. Will try and close the issue. 
Ty.

**Comment by thevirtualdj** [comment] 2020-07-16 09:29
![image](https://user-images.githubusercontent.com/102127/87654674-90953080-c757-11ea-86ab-f3cd30bec767.png)
Still having the same problem? 
Did I missconfigured something or?

**Comment by bafonins** [comment] 2020-07-16 11:28
Can confirm that the issue is present in the latest `master`. Basically, the problem here is when creating a new account first we lose the `next` url in the request, which results in always logging in the oauth app regardless if the user visited `host/console` or `host/oauth`. @kschiffer is this something to be implemented in https://github.com/TheThingsNetwork/lorawan-stack/issues/1422 ?

**Comment by kschiffer** [comment] 2020-07-20 12:41
Indeed, this is essentially a duplicate of TheThingsIndustries/lorawan-stack#1968 (this should be an open source issue...)  and is something that really really needs to be fixed ASAP.

@thevirtualdj we are aware of this issue and looking into possible fixes.

**Comment by kschiffer** [comment] 2020-07-20 12:45
> [**@kschiffer**](https://github.com/kschiffer) is this something to be implemented in [#1422](https://github.com/TheThingsNetwork/lorawan-stack/issues/1422) ?

As far as retaining the `next` query parameter goes, yes, I will make sure to add this.

**Comment by thevirtualdj** [comment] 2020-08-12 07:11
Still present in 3.9.0

**Comment by johanstokking** [comment] 2020-08-24 15:15
@thevirtualdj we're working on it, please bear with us.

**Closed** 2021-03-01 14:31 UTC
Labels: c/console, c/identity server, ui/web
