### ISSUE TITLE
Missing RX metadata in device activations

### ISSUE THREAD

**Issue by NicolasMrad** [TheThingsNetwork/lorawan-stack#6120] opened 2023-03-22 16:08 UTC
### Summary

missing RX metadata in the (non verbose) device traffic events

### Current Situation

Can’t see the RX metadata of join-requests, maybe due to the routing policy or duty cycle

### Why do we need this? Who uses it, and when?

To be able to see the RX metadata of join-requests

### Proposed Implementation

up for discussion when triaged

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing the feature after the proposal above is approved.
- [ ] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by johanstokking** [comment] 2023-03-28 10:41
The issue is that when a device activates while looking at the application or device traffic view in the Console, a join-accept event is shown. This, for good reasons, does not include RX metadata of the join-request.

It would be very helpful to see RX metadata to figure out why a device didn't receive the join-accept. So what would be helpful, is showing join-request events.

From what I understood from an offline discussion, is that the verbose event stream does include the join-request message, at least on the device level and maybe also on the application level. I'll check this out. If that is indeed the case, we can probably just close this issue, or decide to show the join-request in non-verbose mode.

**Comment by adriansmares** [comment] 2023-03-28 15:15
For the record, the metadata does exist in the NS events, both in the `ns.up.join.receive` and `ns.up.join.process`. While `receive` contains only the metadata of the initial uplink, `process` is post deduplication and contains everything.

We do not render `receive` or `process` today in the default filter, but we can add it. We can also consider making it propagate to parent (backend-speak for 'appear in the application event stream').

---

With the default Console filter:
![image](https://user-images.githubusercontent.com/36161392/228284879-57215b6a-2824-41ed-b97b-1bc4b3eb4ef3.png)

Without the filter (i.e. verbose events):
![image](https://user-images.githubusercontent.com/36161392/228284962-025e7b81-96fb-43d9-8bcd-7b3aacf877e1.png)

**Comment by johanstokking** [comment] 2023-03-28 16:00
I think that for debugging purposes, it is very helpful to see the join-request. It's the first thing the (OTAA) end device can do. I'd be in favor of including it in the default filter and propagating it to the parent.

**Closed as completed** 2023-06-13 08:11 UTC
Labels: c/network server, status/in-progress
