### ISSUE TITLE
Setting schedule-anytime-delay when creating gateway using CLI not working

### ISSUE THREAD

**Issue by nskydb** [TheThingsNetwork/lorawan-stack#5156] opened 2022-01-28 13:42 UTC
Hi everyone

#### Summary

I am trying to create gateways on the stack using the CLI as follows:

```
ttn-lw-cli gateways create test-gw-01 --gateway-id test-gw-01 --gateway-eui 1000000000000001 --require-authenticated-connection --frequency-plan-id EU_863_870_TTN --organization-id myorg --schedule-anytime-delay 530ms --name "Test Gateway 1" --description "some gateway"
```

However, this fails with the following error:

```
error:cmd/ttn-lw-cli/internal/util:flag_value (invalid flag value)
    schedule-anytime-delay=time: invalid duration "<time.Duration Value>"
    correlation_id=26e7358ddfcb4f618d5c991df9e20121
```

We use this command in a script, and with older versions of ttn-lw-cli it worked perfectly (3.12.2). So I guess something changed in the code that broke it. However, I am not a Go developer, so I could not find the bug in the code.

According to the CLI help, the format should be like `1h2m3s`, but this does also not work (I tried `0h0m0s530ms`). I have seen that [this commit](https://github.com/TheThingsNetwork/lorawan-stack/commit/edd15956ebe295e8c053dad916f222c66f73f286) changed something regarding the duration types. Am I doing something wrong or is this a bug?

Thanks a lot in advance for your feedback.

#### Steps to Reproduce

1. Login to CLI
2. Execute command from above
3. Watch the error output

#### What do you see now?

```
error:cmd/ttn-lw-cli/internal/util:flag_value (invalid flag value)
    schedule-anytime-delay=time: invalid duration "<time.Duration Value>"
    correlation_id=26e7358ddfcb4f618d5c991df9e20121
```

#### What do you want to see instead?

Successful gateway creation with the desired parameters.

#### Environment
ttn-lw-cli version: 

```
The Things Network Command-line Interface: ttn-lw-cli
Version:             3.17.1
Build date:          2022-01-12T12:16:36Z
Git commit:          10da1157c
Go version:          go1.17.5
OS/Arch:             darwin/amd64
```

#### How do you propose to implement this?

Correctly parse the given argument

#### How do you propose to test this?

Add some unit tests for the specific argument "schedule-anytime-delay" with different (correct and incorrect) input values

#### Can you do this yourself and submit a Pull Request?

Unfortunately not, since I do not know Go well enough to debug and fix this.

**Comment by pgalic96** [comment] 2022-02-04 12:36
Hey @nskydb ! Thanks for the extensive bug report. Indeed this is a bug caused by the newest changes to how the duration flags are handled. I pushed a fix and it will hopefully land in the next release.

**Closed as completed** 2022-02-04 14:01 UTC
Labels: bug
