### ISSUE TITLE
Container can't run on armhf architecture

### ISSUE THREAD

**Issue by zamashal** [TheThingsNetwork/lorawan-stack#2062] opened 2020-02-26 18:24 UTC
#### Summary

In an attempt to set up the stack on systems with armhf architecture (i.e. Raspberry Pi), I was faced with the following error:
```
standard_init_linux.go:211: exec user process caused "exec format error"
```
I suspect this error is indicating that the docker container is only built for x86_64 architecture. Would TTN Stack team be interested in extending the compatibility to armhf and 32-bit systems?

#### Steps to Reproduce

1. Use a Raspberry Pi or any other armhf/32-bit system.
2. Install docker and docker-compose on the system.
3. Run ``docker-compose pull``
4. Initialize the stack using the command: ``docker-compose run --rm stack is-db init``

#### What do you see now?

You will see the following error: ``standard_init_linux.go:211: exec user process caused "exec format error"``

#### What do you want to see instead?

successful initialization and run of the stack container

#### Environment

using the latest stack (3.5.3).
OS example:
```
Linux version 4.9.150-imx6-sr (abuild@c17985c599fa) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 
armv7l GNU/Linux
```
#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by johanstokking** [comment] 2020-02-27 08:35
Duplicate of https://github.com/TheThingsNetwork/lorawan-stack/issues/510

**Closed by johanstokking** 2020-02-27 08:35 UTC
