### ISSUE TITLE
Improve UX receiving error code 6 - (device) Entity Already Exists

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#2595] opened 2020-05-26 09:37 UTC
#### Summary
Users get too often error Code 6 - Entity already exists.

This happens when:
- Development devices are used by multiple people
- A colleague already configured a device without giving others access
- Handout at conferences which appears to be registered already

![image005](https://user-images.githubusercontent.com/17290639/82884174-acdcd400-9f43-11ea-955b-1bca15d5f250.jpg)

...

#### Why do we need this?
Bad user experience, people don't manage to connect their sensors
Expensive sensors become useless because an unknown person already claimed it
People prefer V2 over V3 because this issues doesn't occur there

...

#### What is already there? What do you see now?
Open for discussion. Some thoughts:

1. Allow device to be registered multiple times.
2. Add a checkbox: "development device - enable sensor to be registered multiple times"
3. Add a checkbox when the error code occurs: "device is already registered, I hereby claim I am the rightful owner of this device"
4. Add a description in the error message with info about where and by whom the sensor is registered.
5. ...

...

#### Environment
v3.8.1+

...

#### How do you propose to implement this?
Start discussion first.

...

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?
@johanstokking @htdvisser 

...

**Comment by johanstokking** [comment] 2020-05-26 09:38
Duplicate of https://github.com/TheThingsIndustries/lorawan-stack/issues/2130

Let's discuss there first

**Closed by johanstokking** 2020-05-26 09:38 UTC
Labels: discussion
